### ISSUE TITLE
Adopt generic network functions from other projects

### ISSUE THREAD

**Issue by clhunsen** [se-sic/coronet#11]
There are a bunch of functions from other projects that should be incorporated and adopted into this project.

Some functionalites that we should transfer here:
- [x] discretization of project-level networks (time-based or activity-based)
- [x] combination/addition of networks (see https://github.com/se-passau/dev-network-growth/blob/master/util.R#L64, #61, #15, and #98; PR #115)
- [x] core/peripheral developers (also needed for #34, added in PR #51)
- [ ] universal network-construction function (see https://github.com/se-passau/dev-network-growth/pull/39)
- [x] motif identification (see PR #42)
