### ISSUE TITLE
Update core-peripheral module

### ISSUE THREAD

**Issue by clhunsen** [se-sic/coronet#70]
- [x] overhaul documentation
- [x] fulfill coding conventions
- [x] only use `author.name` column when calling `get.commit.data` in `get.author.commit.count` function [(see comment below)](https://github.com/se-passau/codeface-extraction-r/issues/70#issuecomment-424668012)
- [x] #148 
- [x] add `get.author.mail.count` function (similarly to `get.author.commit.count`) etc. [(see comment below)](https://github.com/se-passau/codeface-extraction-r/issues/70#issuecomment-424668069) _(edit T.B. 2021-07: done in PR #209)_
- [x] Move functions `get.*.commit.count` or else. _(edit T.B. 2021-07: done in PR #194)_ 
- [x] `get.commit.data` is superfluous, the splitting module should be used directly by giving specific bins _(edit T.B. 2021-07: done in PR #163)_
- [x] ~~https://github.com/se-passau/codeface-extraction-r/pull/51#discussion_r132924711~~ _(edit T.B. 2021-07: obsolete after removing `get.commit.data`)_
- [x] consider to substitute `Date` objects with `POSIXct` objects _(edit T.B. 2021-07: seems to be already done...)_
- [x] incorporate pending changes from https://github.com/se-passau/dev-release-peripheral/pull/6 _(edit T.B. 2021-07: alredy done)_
- ... (maybe more)
